import {
    ElRate,
    ElScrollbar,
    ElTable,
    ElTableColumn,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElTag,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElButton,
    ElIcon,
    ElInput,
    ElMessage,
    ElForm,
    ElFormItem,
    ElDialog,
    ElRadioGroup,
    ElRadio,
    ElSelect,
    ElOption,
    ElOverlay,
    ElTooltip,
    ElPopper,
    ElRow,
    ElCol,
    ElCarousel,
    ElCarouselItem,
    ElDatePicker,
    ElImage
} from 'element-plus'

export default (app: any) => {
    app.use(ElRate)
    app.use(ElScrollbar)
    app.use(ElTable)
    app.use(ElTableColumn)
    app.use(ElBreadcrumb)
    app.use(ElBreadcrumbItem)
    app.use(ElTag)
    app.use(ElDropdown)
    app.use(ElDropdownItem)
    app.use(ElDropdownMenu)
    app.use(ElButton)
    app.use(ElIcon)
    app.use(ElInput)
    app.use(ElMessage)
    app.use(ElForm)
    app.use(ElFormItem)
    app.use(ElDialog)
    app.use(ElRadioGroup)
    app.use(ElRadio)
    app.use(ElSelect)
    app.use(ElOption)
    app.use(ElOverlay)
    app.use(ElTooltip)
    app.use(ElPopper)
    app.use(ElRow)
    app.use(ElCol)
    app.use(ElCarousel)
    app.use(ElCarouselItem)
    app.use(ElDatePicker)
    app.use(ElImage)
}
